name: Nightly Build

permissions:
  contents: write

on:
    schedule:
      - cron: '00 23 * * *'
    workflow_dispatch:

jobs:
  build-frzyc-master:
    uses: ./.github/workflows/nightly.yml
    with:
      remote: frzyc
      repository: frzyc/genshin-optimizer
      ref: master
      build-flags: '--profile --source-map'
    secrets:
      ssh_key_genshindata: ${{ secrets.ssh_key_genshindata }}
  build-eeeqeee-tc-opt:
    uses: ./.github/workflows/nightly.yml
    with:
      remote: eeeqeee
      repository: eeeqeee/genshin-optimizer
      ref: tc-opt
    secrets:
      ssh_key_genshindata: ${{ secrets.ssh_key_genshindata }}
